services:
  jarvis_brain:
    container_name: jarvis_brain
    build:
      context: .
      args:
        - BRAIN_PORT=${BRAIN_PORT}
    image: joynerlee/jarvishomeassist_brain:latest
    env_file: .env
    ports:
      - "${BRAIN_PORT}:${BRAIN_PORT}"
    restart: unless-stopped
    volumes:
      - /:/host:ro
    depends_on:
      - jarvis_memory
    networks:
      - jarvis_home_assist
  jarvis_memory:
    image: postgres:18-alpine
    container_name: jarvis_memory
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - jarvis_home_assist

networks:
  jarvis_home_assist:
    driver: bridge
