services:
  jarvis_brain:
    container_name: jarvis_brain
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /:/host:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    depends_on:
      - jarvis_memory
    networks:
      - jarvis_home_assist
  jarvis_memory:
    image: postgres:18-alpine
    container_name: jarvis_memory
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - jarvis_home_assist

networks:
  jarvis_home_assist:
    driver: bridge
